services:
  - type: web
    name: route-mapper
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_web:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_MODE
        value: web